### ISSUE TITLE
Do you have reason for using `class.defaultProps = defaultProps` instead of `static defaultProps`? 

### ISSUE THREAD

**Issue by SoYoung210** [Yapp-Web5/Druwa-WEB#21]
Hi! Im Soyoung, FE developer in YAPP Team4.
Prior to my question, I would appreciate your understanding that my English is not great. 

I have seen that you have created default Props for all components in the following way:

1.
https://github.com/Yapp-Web5/Druwa-WEB/blob/286f9fd2e10de915816697565041ee68bfc66bbf/src/components/Highlight/Highlight.jsx#L8

```jsx
Highlight.defaultProps = defaultProps;
Highlight.propTypes = propTypes;
```

I wrote the code in the same way as above, but recently I was recommended the following method.

2.
```jsx
class Slider extends PureComponent {
  static propTypes = {
    className: PropTypes.string,
    max: PropTypes.number.isRequired,
    onChange: PropTypes.func.isRequired,
    value: PropTypes.number.isRequired
  }
  static defaultProps = {
    className: ""
  }
}
{ /* ... skip */ }
```

Im not good at Vanila Javascript, so i want to know **what difference** between 1 and 2. 

I read some documents, but I did not understand well.
This is the article I read. 

> https://medium.com/@martin_hotell/react-typescript-and-defaultprops-dilemma-ca7f81c661c7
https://engineering.musefind.com/our-best-practices-for-writing-react-components-dec3eb5c3fc8

If you have a special reason about using `1`, please explain to me. It will help my javascript skills.

Thx!

**Comment by nayunhwan** [comment]
Hi, @SoYoung210 

I think that it has no huge difference that between `case 1` and `case 2`.
But, It seems to be better `case2` than `case1` when use only `JavaScript` without `TypeChecker` like `TypeScript` or `Flow`.

The reason that I had written as `case 1` is that I don't use `propTypes` anymore because the `propTypes` enough can be replaced by [**Flow**](https://flow.org/) or [**TypeScript**](https://www.typescriptlang.org/).

Personally, I think that when writing as `case 1`, can change more easily to **Type World**.

Look at this case

**Without TypeChecker**
```js
const defaultProps = {
   ...
};
const propTypes = {
   value: PropTypes.number.isRequired
};

class Example extends PureComponent {
  constructor(props) {
    super(props);
  }
```

**Changed to TypeScript**
```ts
export interface Props {
   value: number
}

export interface State {
   ...
}

class Example extends PureComponent<Props, State> {
  public static defaultProps: Partial<Props> = {};

  public constructor(props: Props) {
    super(props);
  }
```

**Comment by nayunhwan** [comment]
After **Deview2018**, I think that the **TypeChecker** is essential, not optional anymore. If you are hard to adopt **TypeScript**. I think the **Flow** also can be another awesome way instead of **TypeScript**.
